### ISSUE TITLE
Close submenu script no longer works with jquery 1.9

### ISSUE THREAD

**Issue by sstudebaker** [iprignano/tendina#11]
Hi again. I have to use jquery 1.9 for a slideshow function and that has broken the script you gave to me to close the submenu when mouse leaves the element. Is there another way to do this that would work with more recent jquery release? You were so helpful before I thought I should ask in case you might have an idea how to fix this.

Page with issues http://csoutdoorprogram.org/fall-salmon-river-rafting-trip/
user: ola
pass: 1973

The script you gave me is here:
// Here you bind the mouseout event on the tendina helper class
		$(document).on('mouseout', '.tendina', function() {
			setTimeout(function() {
			if (!$('.tendina').is(':hover')) {
					$('.tendina').find('> li > ul').slideUp().parent().removeClass('selected');
				}
			}, 500);
		});
		</script>

**Comment by iprignano** [comment]
Hey @sstudebaker,

The solution in pretty straightforward and a quick Google search would give you tons of results. One of them is [here](https://stackoverflow.com/questions/16497457/ishover-is-broken-as-of-jquery-1-9-how-to-fix).

Please don't use this GitHub issue system as a personal problem solver – this is made to solve bugs strictly related to Tendina. If you need help with your code I'd suggest you to use appropriate websites, like [stackoverflow](https://stackoverflow.com/). 

Thank you! :)

Ivan
