### ISSUE TITLE
Follow a Link with active 'showAll' Method

### ISSUE THREAD

**Issue by vismagine** [iprignano/tendina#12]
With an active 'showAll' Method it is just possible to follow a link within a submenu by doubleclick the link, here my [example](http://www.c-und-d.de/subskription/). It seems that the first click is the one for opening the submenu 'virtualy' and just the second one follows the link.

Is there a way to follow the link with a **simple** click within submenus that were pre-opened with 'showAll'?

Many thanks in advance for your support.

Cris

**Comment by iprignano** [comment]
Hey Cris,

nice catch! I'm going to try and figure a solution to it in the next days.

Thank you!

**Comment by iprignano** [comment]
Cris,

with the latest `0.11.1` version, that you can download straight from this repo, the issue should be fixed. I'm going to close this issue, but let me know if there are any problems!

**Comment by vismagine** [comment]
It works great now. Thank you very much for your fast reaction on this issue.
