### ISSUE TITLE
Feature: add cookie or localstorage for menu state

### ISSUE THREAD

**Issue by lenamtl** [iprignano/tendina#14]
Hi,
Are you planning to add a way to remember menu state using 
cookie or localstorage?

**Comment by iprignano** [comment]
Hey lenamtl,

No, I won't probably do that – it would add too much complexity to the code for a feature which a simple library as Tendina shouldn't have.

However, if you really want to implement that, it should be fairly easy as the API could help you – just use the `openCallback` to save the currently active menu in the localStorage/cookie and `activeMenu` to get it back when you initialise Tendina.

Hope this helps!
