### ISSUE TITLE
What if parent heading is also a link?

### ISSUE THREAD

**Issue by terotik** [iprignano/tendina#16]
It would be nice that the menu parent could also be a link. My document structure is such that every item in the list is also a link to a page. Now the link of the parent item gets suppressed when the sub-menu is opened.

**Comment by iprignano** [comment]
Yeah, I thought about this but never implemented it – I'll look into it and see if I can do something.
Thanks for the input!

**Comment by iprignano** [comment]
Thinking about it, I'm not sure this is a real problem – you want to have "top-level" links on your menus that have child menus. Is this right?

In that case, clicking on the link would redirect you to another page and not actually open the submenu –this means that to make your navigation usable you always need to show your child menus. So I suppose you don't really want/need something like Tendina. Or am I missing your point?

**Comment by terotik** [comment]
@iprignano That's correct. This technique would require use of ´activeMenu´-parameter. 

So the parent in the menu would redirect you to a page where that item would be marked as ´activeMenu´, hence opened. Clicking again on it would just return to that page, not close the menu. The item would only close if another link on the same level (sibling) or level above (parent) was clicked.

Not the most elegant and useful option, I agree, and I understand if it's something you don't want to add to Tendina. I have a fairly complex page structure and each parent link is an introductory chapter page to that section, and I wouldn't want to add extra headers in between for the menu. Still, it would be useful to have something like Tendina taking care of the collapsing of unopened branches. As the tree can get quite long and complex.

Cheers!

**Comment by iprignano** [comment]
@terotic Ah, I get it now. Yes, it's quite a complex behaviour and I'm not sure Tendina should take it into account – it sounds like it's edge-casey enough to deserve a custom menu logic.

What you could do to work around it would be duplicating the "heading" menu and hide/show one or another based on your necessity. Something like this:

``` html
<ul class="tendina">
  <!-- Heading without children (just redirects you to the page) -->
  <li class="hide"><a href="http://chapter.com">Chapter 1</a></li>
  <!-- Heading with children (opens/closes submenus via Tendina) -->
  <li class="show"><a href="#">Chapter 1</a>
    <li>Sub 1</li>
    <li>Sub 2</li>
  </li>
  [...]
</ul>
```

Obviously this would mean that you would have to build your own logic around the `hide` and `show` classes. So yeah, not very elegant but you could get away with it :)

I'm going to close this as I think Tendina should be kept quite simple and straightforward. Sorry about that and good luck with your menu!
